# docker-compose.production.yml

volumes:
  food_data_prod:
  static_volume:
  media_volume:

services:
  food_db:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - food_data_prod:/var/lib/postgresql/data
    restart: always

  backend:
    image: wwwkka/food_back:latest
    env_file: .env
    depends_on:
      - food_db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
      - ./data:/app/data
    restart: always

  frontend:
    image: wwwkka/food_front:latest
    # Копируем билд фронта в общий статик-том и держим контейнер живым
    command: >
      sh -c '
        if [ -d /usr/share/nginx/html ]; then
          cp -r /usr/share/nginx/html/. /frontend_static/ || true;
        elif [ -d /app/build ]; then
          cp -r /app/build/. /frontend_static/ || true;
        fi;
        tail -f /dev/null
      '
    volumes:
      - static_volume:/frontend_static
    restart: always

  gateway:
    image: wwwkka/food_gate:latest
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
      - ./docs:/docs
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
